### PR TITLE
Improve safety and ergonomics

### PR DESCRIPTION
**Pull request by yuri91**
Hi,
I am working on a library based on this and tdlib-sys, and I found some issues both from a safety and ergonomics point of view.
Here you can see all my modifications, but if you prefer I can split this PR into multiple ones.
There are 3 main things here:
- Adding the logging functions recently exposed in tdlib-sys
- Fixing some errors in  handling strings in ffi 
- Adding the ability to split the client in a ClientSender and a ClientReceiver, so it is possible to use the library safely from multiple threads

Again, I am putting everything here so you can see the whole picture, but I can easily split it in 3, and you can of course accept only a part.

P.S.:  This currently does not compile because tdlib-sys 0.1.3 is not on crates.io, and so the logging functions are not defined. I tested it with a local version of the latest master.
There is an issue about it here -> https://github.com/mersinvald/tdjson-sys/issues/4

### CODE REVIEW

**Comment by mersinvald** [comment]
Thanks, @yuri91. 
I'll get to it tomorrow afternoon after publishing the 0.1.3.

**Review by mersinvald — APPROVED** [review]

**Comment by mersinvald** [comment]
@yuri91 thanks! Looks awesome.
Please update the PR with the sys 0.1.3, and bump the version of the crate since the change is breaking public API. I'll be happy to merge and publish.

**Comment by yuri91** [comment]
Nice! I updated the dependency and bumped the version to 0.2.0!

**Comment by mersinvald** [comment]
Sorry for the delay, version is uploaded.

If you're willing to continue development of these bindings (e.g more usable higher-level interface for writing tdlib-based clients), I could give you write access to the repo and crates.io package.

**Comment by yuri91** [comment]
That would be nice!

My other work is on https://github.com/yuri91/tdlib-futures , where I am building a futures API and using Rust types instead of json strings for messages and responses.

I think that this crate is mostly fine now (maybe I can move some higher level methods from tdlib-futures but I am not sure).

**Pull request merged**
